### ISSUE TITLE
.Net 6.0 support?

### ISSUE THREAD

**Issue by Desync3** [Runnin-N-Gunnin/WinForms-Theme-Pack#2]
Is there anyway to use these in .net 6.0?

**Comment by Runnin-N-Gunnin** [comment]
Hello Desync3,

I'm not sure to be honest - I use .NET Framework personally. I would recommend trying and then manually go through and solve the errors you might get.

If you can't figure it out copy and paste the error(s) here and I'll try to help you further.

**Comment by Desync3** [comment]
Oh okay, i understand. I dont really get any errors its just not allowing me to add it since its .net framework. .NET is just garbage tbh, i will stick to .NET Framework and uninstall .net. Thanks
